# Generated by Django 5.2.6 on 2025-09-29 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('condominio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('alquiler', 'Alquiler'), ('reserva_area', 'Reserva de Área Común'), ('expensa_ordinaria', 'Expensa Ordinaria'), ('multa', 'Multa'), ('servicio', 'Servicio')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('es_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('parcial', 'Parcial')], default='pendiente', max_length=20)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('periodo', models.CharField(max_length=7)),
                ('residencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.residencia')),
            ],
            options={
                'unique_together': {('residencia', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='DetalleCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.cuota')),
                ('expensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.expensa')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_incidente', models.DateField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usuario')),
                ('detalle_cuota', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.detallecuota')),
                ('residencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='condominio.residencia')),
                ('residente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.residente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], max_length=100)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.cuota')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.residente')),
            ],
        ),
    ]
