# Generated by Django 5.2.6 on 2025-09-29 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('piscina', 'Piscina'), ('salon_eventos', 'Salón de Eventos'), ('gimnasio', 'Gimnasio'), ('parrilla', 'Quincho/Parilla'), ('cancha', 'Cancha Deportiva'), ('meeting', 'Meeting Room'), ('study', 'Study Room'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('capacidad', models.PositiveIntegerField(default=10)),
                ('hora_apertura', models.TimeField(default='08:00')),
                ('hora_cierre', models.TimeField(default='22:00')),
                ('tiene_costo', models.BooleanField(default=False)),
                ('costo_normal', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('costo_fin_semana', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('permitido_para_inquilinos', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('mantenimiento', 'En Mantenimiento')], default='disponible', max_length=20)),
                ('esta_activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Área Común',
                'verbose_name_plural': 'Áreas Comunes',
            },
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_contrato', models.CharField(choices=[('propiedad', 'Propiedad'), ('alquiler', 'Alquiler'), ('comodato', 'Comodato')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('esta_activa', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('esta_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Residencia',
                'verbose_name_plural': 'Residencias',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_unidad', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('local', 'Local Comercial'), ('oficina', 'Oficina'), ('otro', 'Otro')], max_length=20)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('edificio', models.CharField(blank=True, max_length=100, null=True)),
                ('piso', models.CharField(blank=True, max_length=10, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('dimensiones', models.CharField(max_length=100)),
                ('habitaciones', models.PositiveIntegerField(default=1)),
                ('banios', models.PositiveIntegerField(default=1)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_alquiler', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ubicacion', models.TextField()),
                ('caracteristicas', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('mantenimiento', 'En Mantenimiento'), ('reservada', 'Reservada')], default='disponible', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('esta_activa', models.BooleanField(default=True)),
                ('foto_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='Habitante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('ci', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('tipo_parentesco', models.CharField(choices=[('conyuge', 'Cónyuge'), ('hijo', 'Hijo/Hija'), ('padre', 'Padre/Madre'), ('hermano', 'Hermano/Hermana'), ('otro_familiar', 'Otro Familiar'), ('amigo', 'Amigo/Conocido')], max_length=20)),
                ('es_contacto_emergencia', models.BooleanField(default=False)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('esta_activo', models.BooleanField(default=True)),
                ('residente_titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitantes', to='accounts.residente')),
            ],
            options={
                'verbose_name': 'Habitante',
                'verbose_name_plural': 'Habitantes',
            },
        ),
        migrations.CreateModel(
            name='ReservaAreaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('reservada', 'Reservada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('area_comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominio.areacomun')),
            ],
            options={
                'verbose_name': 'Reserva de Área Común',
                'verbose_name_plural': 'Reservas de Áreas Comunes',
            },
        ),
    ]
