# Generated by Django 5.2.6 on 2025-09-29 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('condominio', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaareacomun',
            name='cuota_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.cuota'),
        ),
        migrations.AddField(
            model_name='reservaareacomun',
            name='detalle_cuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.detallecuota'),
        ),
        migrations.AddField(
            model_name='reservaareacomun',
            name='residente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.residente'),
        ),
        migrations.AddField(
            model_name='residencia',
            name='residente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residencias', to='accounts.residente'),
        ),
        migrations.AddField(
            model_name='habitante',
            name='residencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitantes', to='condominio.residencia'),
        ),
        migrations.AddField(
            model_name='residencia',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residencias', to='condominio.unidad'),
        ),
        migrations.AlterUniqueTogether(
            name='residencia',
            unique_together={('unidad', 'esta_activa')},
        ),
    ]
