# Generated by Django 5.2.6 on 2025-09-29 06:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('esta_activo', models.BooleanField(default=True)),
                ('foto_url', models.URLField(blank=True, null=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='accounts.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('copropietario', 'Copropietario'), ('inquilino', 'Inquilino'), ('propietario', 'Propietario')], max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto_emergencia_personal_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_emergencia_personal_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto_emergencia_personal_parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('tiene_vehiculo', models.BooleanField(default=False)),
                ('detalle_vehiculos', models.TextField(blank=True, null=True)),
                ('tiene_mascota', models.BooleanField(default=False)),
                ('detalle_mascotas', models.TextField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residente', to='accounts.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_permisos', to='accounts.permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_permisos', to='accounts.rol')),
            ],
            options={
                'verbose_name': 'Rol-Permiso',
                'verbose_name_plural': 'Roles-Permisos',
                'unique_together': {('rol', 'permiso')},
            },
        ),
    ]
