# Generated by Django 5.2.6 on 2025-09-29 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('condominio', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('tipo', models.CharField(choices=[('general', 'General'), ('importante', 'Importante'), ('urgente', 'Urgente'), ('mantenimiento', 'Mantenimiento')], default='general', max_length=20)),
                ('para_todos', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('enviar_push', models.BooleanField(default=False)),
                ('push_enviado', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usuario')),
                ('para_residencias', models.ManyToManyField(blank=True, to='condominio.residencia')),
                ('para_roles', models.ManyToManyField(blank=True, to='accounts.rol')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('tarea', 'Tarea'), ('pago', 'Pago'), ('reserva', 'Reserva'), ('multa', 'Multa'), ('sistema', 'Sistema'), ('aviso', 'Aviso')], max_length=20)),
                ('entidad_tipo', models.CharField(blank=True, max_length=50)),
                ('entidad_id', models.CharField(blank=True, max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_leida', models.DateTimeField(blank=True, null=True)),
                ('push_enviado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usuario')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('ordinaria', 'Ordinaria'), ('extraordinaria', 'Extraordinaria')], default='extraordinaria', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('fecha_tomada', models.DateTimeField(blank=True, null=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('area_comun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='condominio.areacomun')),
                ('asignado_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.rol')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_creadas', to='accounts.usuario')),
                ('residencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='condominio.residencia')),
                ('tomada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_tomadas', to='accounts.usuario')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
